"""Merge deterministic Synthea batches into one compact cohort with full provenance.

Every batch was generated by `synthea_batch_runner.py` with its own recorded seed, converted
immediately to the MetaboGuard longitudinal schema, hashed, and had its raw export deleted
before the next batch. This script concatenates the compact batches, deduplicates patients,
validates the result and writes a manifest listing every seed and batch hash.

Usage::

    python merge_synthea_batches.py --batch-dir /tmp/synthea_batches --output-dir /tmp/synthea_pool
"""

from __future__ import annotations

import argparse
from datetime import UTC, datetime
import json
from pathlib import Path
import sys

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))

from longitudinal_schema import (  # noqa: E402
    CapabilityState,
    SCHEMA_VERSION,
    frame_fingerprint,
    validate_event_frame,
)
from synthetic_longitudinal import SYNTHEA_CONFIG  # noqa: E402


def merge(batch_dir: str | Path, output_dir: str | Path, fixture_patients: int = 6) -> dict:
    batch_root = Path(batch_dir)
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    records = [json.loads(path.read_text()) for path in sorted(batch_root.glob("batch_*.json"))]
    frames, used = [], []
    seen: set[str] = set()
    for record in records:
        if record.get("status") not in {None, "ok"}:
            continue
        path = batch_root / f"events_batch_{record['batch']:02d}.csv"
        if not path.exists():
            continue
        frame = pd.read_csv(path, low_memory=False)
        # Deduplicate across batches: a patient id already seen is dropped entirely.
        duplicates = sorted(set(frame["patient_id"].unique()) & seen)
        if duplicates:
            frame = frame[~frame["patient_id"].isin(duplicates)]
        seen |= set(frame["patient_id"].unique())
        frame["source_batch"] = record["batch"]
        frame["source_seed"] = record["seed"]
        frames.append(frame)
        used.append({**record, "duplicate_patients_dropped": len(duplicates)})

    if not frames:
        raise RuntimeError("No convertible batches found.")
    events = pd.concat(frames, ignore_index=True)
    for column in ("observation_timestamp", "index_date", "event_date", "censoring_date"):
        events[column] = pd.to_datetime(events[column], errors="coerce", utc=True, format="ISO8601")

    validated, report = validate_event_frame(
        events.drop(columns=["source_batch", "source_seed"]),
        dataset_name="synthea_pooled_events",
        strict=True,
    )
    # Validation can drop rows, so provenance is re-attached by patient id rather than position.
    provenance = (
        events[["patient_id", "source_batch", "source_seed"]]
        .drop_duplicates(subset=["patient_id"])
        .set_index("patient_id")
    )
    validated["source_batch"] = validated["patient_id"].map(provenance["source_batch"])
    validated["source_seed"] = validated["patient_id"].map(provenance["source_seed"])

    events_path = output / "patient_events.csv"
    validated.to_csv(events_path, index=False)
    (output / "event_validation_report.json").write_text(json.dumps(report.as_dict(), indent=2, default=str))

    fixture_ids = sorted(validated["patient_id"].unique())[:fixture_patients]
    fixture = validated[validated["patient_id"].isin(fixture_ids)]
    fixture.to_csv(output / "fixture_patient_events.csv", index=False)

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "dataset_name": "synthetic_longitudinal_synthea_pooled",
        "created_at": datetime.now(UTC).isoformat(),
        "capability_state": CapabilityState.SIMULATION_ONLY_LONGITUDINAL.value,
        "simulation_only": True,
        "cohort_class": "simulation_ordinary_incidence",
        "generator": {
            "used_generator": "synthea",
            "release": SYNTHEA_CONFIG["pinned_release"],
            "jar_sha256": SYNTHEA_CONFIG["jar_sha256"],
            "runtime": SYNTHEA_CONFIG["recorded_runtime"],
            "state": SYNTHEA_CONFIG["state"],
            "age_filter": SYNTHEA_CONFIG["age_filter"],
            "index_rule": SYNTHEA_CONFIG["index_rule"],
            "enrichment_declared": False,
            "batching": (
                "Generated in deterministic batches; each batch converted immediately and its raw "
                "export deleted before the next batch to bound peak disk."
            ),
            "batches": used,
            "seeds": [record["seed"] for record in used],
        },
        "row_counts": {
            "event_rows": int(len(validated)),
            "patients": int(validated["patient_id"].nunique()),
            "fixture_rows": int(len(fixture)),
            "fixture_patients": int(fixture["patient_id"].nunique()),
        },
        "fingerprints": {
            "events": frame_fingerprint(validated.drop(columns=["source_batch", "source_seed"])),
            "fixture": frame_fingerprint(fixture.drop(columns=["source_batch", "source_seed"])),
        },
        "notes": [
            "SIMULATION ONLY. Not real patients. Cannot establish real-world calibration, "
            "clinical utility or early detection.",
            "Ordinary Synthea incidence: no enrichment, no reweighting, no augmentation. "
            "Event counts at short horizons are correspondingly small and some horizons abstain.",
            "Synthea methodology DOI 10.1093/jamia/ocx079; validity limits DOI 10.1186/s12911-019-0793-0.",
        ],
    }
    (output / "dataset_manifest.json").write_text(json.dumps(manifest, indent=2, default=str))
    return {
        "output_dir": str(output),
        "batches_used": len(used),
        "patients": manifest["row_counts"]["patients"],
        "rows": manifest["row_counts"]["event_rows"],
        "validation_status": report.as_dict()["status"],
        "seeds": manifest["generator"]["seeds"],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batch-dir", default="/tmp/synthea_batches")
    parser.add_argument("--output-dir", default="/tmp/synthea_pool")
    arguments = parser.parse_args()
    print(json.dumps(merge(arguments.batch_dir, arguments.output_dir), indent=2))


if __name__ == "__main__":
    main()